/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 acai_bowl.glb -T
Author: Jeremy E. Grayson (https://sketchfab.com/JeremyGrayson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/acai-bowl-a69e652174fa43a4adc58828d13bdfe5
Title: Acai Bowl
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AcaiBowl(props) {
  const { nodes, materials } = useGLTF('/models/acai_bowl-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/acai_bowl-transformed.glb')
