/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 dry_flower.glb -T
Author: Eisuke Komatsu (https://sketchfab.com/kayaaku)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dry-flower-9c5bea0d812a459297b805ff7658b7e0
Title: Dry flower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function DryFlower(props) {
  const { nodes, materials } = useGLTF('/models/dry_flower-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.model_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.model_u1_v1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.model_u1_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.model_u1_v1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.model_u1_v1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.model_u1_v1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.model_u1_v1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.model_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/dry_flower-transformed.glb')
