/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 spoon.glb -T
Author: LBOrion (https://sketchfab.com/LBOrion)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spoon-3e9888770c32430cb9385cf5779f370d
Title: Spoon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Spoon(props) {
  const { nodes, materials } = useGLTF('/models/spoon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/spoon-transformed.glb')
